spring:
    datasource:
        url: jdbc:mysql://localhost:3306/crm_app
        username: root
        password: tsthtlvq1994
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect